# Generated by Django 4.1.13 on 2024-02-23 13:32

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar_user_date_of_birth_user_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='default_image.jpg', null=True, upload_to=users.models.user_avatar_path),
        ),
    ]
