version: '3'

services:
  piston:
    container_name: piston-api
    image: ghcr.io/engineer-man/piston
    networks:
      - algolabs_net
    ports:
      - "2000:2000"
    volumes:
      - /path/to/piston_data:/piston


  algolabs_backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/algolabs_backend
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - algolab_database
    container_name: algolabs_backend
    networks:
      - algolabs_net

  algolab_database:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - algolab_database:/data/db
    container_name: algolab_database
    networks:
      - algolabs_net

volumes:
  algolab_database:

networks:
  algolabs_net:
