# Generated by Django 4.1.13 on 2024-02-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('input_value', models.TextField()),
                ('expected_output', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='codingchallenge',
            name='function_signature',
            field=models.TextField(),
        ),
    ]
