# Generated by Django 4.1.13 on 2024-03-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
